#!/bin/bash

MINECRAFT_HOME="/opt/minecraft"
MINECRAFT_SRC="/usr/src/minecraft"
MINECRAFT_VERSION=${MINECRAFT_VERSION:-1.13.2}
MINECRAFT_JAR=${MINECRAFT_JAR:-"BungeeCord.jar"}
MINECRAFT_STARTUP_JAR=${MINECRAFT_STARTUP_JAR:-"$MINECRAFT_JAR"}
MINECRAFT_OPTS=${MINECRAFT_OPTS:-"-Xms512M -Xmx512M "}
WORLD_DIR="/var/lib/minecraft"

TMUX_SESSION=spigot

first_run() {
    # Sync files from $MINECRAFT_SRC to $MINECRAFT_HOME. Do this on container's first run.
    if [ -f "/run/first_time" ]; then
        # Ensure that only the relevant plugins are enabled on the server.
        mkdir -p $MINECRAFT_HOME/plugins
        rm $MINECRAFT_HOME/plugins/*.jar*

        rsync -avh --exclude '/world*' $MINECRAFT_SRC/ $MINECRAFT_HOME
        rm /run/first_time
    fi

}

update_permissions() {
    echo "Updating file permissions"
    chown -R minecraft:minecraft $MINECRAFT_HOME $WORLD_DIR
}

run_spigot() {
    echo "TERM is set to $TERM"
    pushd $MINECRAFT_HOME > /dev/null
    echo "Running Minecraft"
    echo "MINECRAFT_OPTS: $MINECRAFT_OPTS"

    MINECRAFT_COMMAND="java $MINECRAFT_OPTS -jar $MINECRAFT_HOME/$MINECRAFT_STARTUP_JAR"

    PARAMS=$@

    echo "Extra parameters: ${PARAMS[@]}"

    if [ "$TERM" == "dumb" ]; then
        >&2 echo "WARNING! Dumb term detected. Switching to noconsole mode."
        >&2 echo "Safe shutdown must be done via /stop chat command."
        MINECRAFT_COMMAND="$MINECRAFT_COMMAND --noconsole ${PARAMS[@]}"
        exec $MINECRAFT_COMMAND
    else
        MINECRAFT_COMMAND="$MINECRAFT_COMMAND ${PARAMS[@]}"
        tmux new -s $TMUX_SESSION "$MINECRAFT_COMMAND"
    fi
}

console_command() {
    COMMAND=$@
    if [ "$TERM" == "dumb" ]; then
        >&2 echo "Console command not supported on a dumb term."
        exit 1
    else
        echo "Executing console command: ${COMMAND[@]}"
        tmux send -t $TMUX_SESSION "${COMMAND[@]}" ENTER
    fi
}

safe_shutdown() {
    echo "Performing safe shutdown..."
    console_command stop
}

case "$1" in
    run)
        shift 1
        first_run
        update_permissions
        trap safe_shutdown EXIT
        run_spigot $@
        ;;
    permissions)
        shift 1
        update_permissions
        ;;
    console)
        shift 1
        console_command $@
        ;;
    *)
        exec "$@"
esac
